---
- name: Pull docker image
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker front-end image
      shell: docker pull arnavdeshpande1/major_project:client1

    - name: pull docker server image
      shell: docker pull arnavdeshpande1/major_project:server1

    - name: Create back-end container

      docker_container:
        name: ts-backend

        image: arnavdeshpande1/major_project:server1

        ports:
          - "5000:5000"

    - name: Create front-end container

      docker_container:
        name: ts-frontend

        image: arnavdeshpande1/major_project:client1

        interactive: true

        ports:
          - "3000:3000"
